// File generated by flutterfire_cli.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: defaultFirebaseOptions,
/// );
/// ```
class DefaultFirebaseOptions {
  /// Web push (FCM on web): Firebase Console → Project settings → Cloud Messaging
  /// → Web Push certificates → Key pair. Paste the **public** key here, then
  /// run `flutterfire configure` so [web] has a real `appId` (not placeholder).
  static const String? webPushVapidPublicKey = null;

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        return android;
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6DP4553YDcC9WltEIyfP1fT03ITbZgQU',
    appId: '1:938624740251:android:afecfde25623c6b8ae4f3e',
    messagingSenderId: '938624740251',
    projectId: 'sago-builders',
    storageBucket: 'sago-builders.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6DP4553YDcC9WltEIyfP1fT03ITbZgQU',
    appId: '1:938624740251:ios:placeholder_id',
    messagingSenderId: '938624740251',
    projectId: 'sago-builders',
    storageBucket: 'sago-builders.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6DP4553YDcC9WltEIyfP1fT03ITbZgQU',
    appId: '1:938624740251:macos:placeholder_id',
    messagingSenderId: '938624740251',
    projectId: 'sago-builders',
    storageBucket: 'sago-builders.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6DP4553YDcC9WltEIyfP1fT03ITbZgQU',
    appId: '1:938624740251:windows:placeholder_id',
    messagingSenderId: '938624740251',
    projectId: 'sago-builders',
    storageBucket: 'sago-builders.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6DP4553YDcC9WltEIyfP1fT03ITbZgQU',
    appId: '1:938624740251:web:placeholder_id',
    messagingSenderId: '938624740251',
    projectId: 'sago-builders',
    storageBucket: 'sago-builders.firebasestorage.app',
  );
}
